# Generated by Django 4.1.7 on 2023-02-16 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_rename_choise_text_choice_choice_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="choice", old_name="question", new_name="question_id",
        ),
    ]
