# Generated by Django 4.1.7 on 2023-02-16 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_rename_question_choice_question_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="choice", old_name="question_id", new_name="question",
        ),
    ]
